import { SiteData } from './types';

export const INITIAL_DATA: SiteData = {
  name: "Richdigital",
  tagline: "Elevate Your Digital Presence",
  description: "We are a premium digital agency crafting world-class experiences for forward-thinking brands.",
  email: "hello@richdigital.com",
  phone: "+1 (555) 123-4567",
  address: "123 Innovation Drive, Tech City, CA 90210",
  socials: {
    facebook: "#",
    twitter: "#",
    instagram: "#",
    linkedin: "#",
  },
  colors: {
    primary: "#4f46e5",
  },
  hero: {
    headline: "We Build Global Digital Experiences That Transform Brands.",
    subheadline: "We blend strategy, design, and technology to build brands that matter in the digital age.",
    ctaText: "Start Your Project",
    backgroundImage: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
  },
  services: [
    { id: '1', icon: 'Code', title: 'Web Development', description: 'High-performance, responsive websites tailored to your brand.' },
    { id: '2', icon: 'Smartphone', title: 'Mobile Apps', description: 'Native and cross-platform mobile applications.' },
    { id: '3', icon: 'Palette', title: 'Branding & Design', description: 'Visual identities that resonate with your audience.' },
    { id: '4', icon: 'TrendingUp', title: 'Digital Marketing', description: 'Data-driven campaigns to grow your reach.' },
    { id: '5', icon: 'Search', title: 'SEO Services', description: 'Optimize your presence and rank higher on search engines.' },
    { id: '6', icon: 'PenTool', title: 'Content Strategy', description: 'Compelling content that drives engagement and conversions.' },
  ],
  portfolio: [
    {
      id: '1',
      title: 'Lumina Finance',
      category: 'FinTech',
      description: 'A complete rebranding and app overhaul for a leading fintech startup.',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      fullContent: 'Full case study details for Lumina Finance...',
    },
    {
      id: '2',
      title: 'Apex Gear',
      category: 'E-Commerce',
      description: 'High-conversion e-commerce store for outdoor performance gear.',
      image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      fullContent: 'Full case study details for Apex Gear...',
    },
    {
      id: '3',
      title: 'Zenith Architecture',
      category: 'Corporate',
      description: 'Minimalist portfolio website for an award-winning architecture firm.',
      image: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      fullContent: 'Full case study details for Zenith...',
    },
    {
      id: '4',
      title: 'EcoSmart Home',
      category: 'IoT App',
      description: 'Smart home energy monitoring dashboard and mobile control center.',
      image: 'https://images.unsplash.com/photo-1558002038-1091a16627a3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      fullContent: 'Full case study details for EcoSmart...',
    },
  ],
  blog: [
    {
      id: '1',
      title: 'The Future of Web Design in 2024',
      author: 'Sarah Jenkins',
      date: 'Oct 12, 2023',
      excerpt: 'Exploring the latest trends in micro-interactions and immersive experiences.',
      content: 'Full article content goes here...',
      image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
    {
      id: '2',
      title: 'Why SEO Matters More Than Ever',
      author: 'Mike Ross',
      date: 'Sep 28, 2023',
      excerpt: 'Understanding the shifting landscape of search algorithms.',
      content: 'Full article content goes here...',
      image: 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
     {
      id: '3',
      title: 'Mastering Mobile User Experience',
      author: 'David Kim',
      date: 'Sep 15, 2023',
      excerpt: 'Key principles for designing intuitive mobile interfaces that convert.',
      content: 'Full article content goes here...',
      image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    },
  ],
  testimonials: [
    { id: '1', name: 'John Doe', role: 'CEO, TechStart', content: 'Richdigital transformed our online presence. Highly recommended!', avatar: 'https://i.pravatar.cc/150?img=1' },
    { id: '2', name: 'Jane Smith', role: 'Marketing Dir, FashionCo', content: 'The team is incredibly talented and responsive. A true partner.', avatar: 'https://i.pravatar.cc/150?img=5' },
    { id: '3', name: 'Robert Fox', role: 'Founder, Omega', content: 'World-class execution and strategy. They just get it.', avatar: 'https://i.pravatar.cc/150?img=3' },
  ],
  faqs: [
    { id: '1', question: 'What is your typical project timeline?', answer: 'Most projects take between 4-12 weeks depending on complexity.' },
    { id: '2', question: 'Do you offer post-launch support?', answer: 'Yes, we offer comprehensive maintenance packages to keep your site secure and updated.' },
    { id: '3', question: 'How do you handle pricing?', answer: 'We work on a project-basis or retainer depending on your needs. Contact us for a quote.' },
    { id: '4', question: 'Can you help with branding?', answer: 'Absolutely. We have a dedicated team for logo design and brand identity.' },
  ],
  team: [
    { id: '1', name: 'Alex Rich', role: 'Founder & CEO', image: 'https://i.pravatar.cc/300?img=11', bio: 'Visionary leader with 15 years of digital experience.' },
    { id: '2', name: 'Maria Garcia', role: 'Creative Director', image: 'https://i.pravatar.cc/300?img=9', bio: 'Award-winning designer obsessed with typography.' },
    { id: '3', name: 'David Kim', role: 'Lead Developer', image: 'https://i.pravatar.cc/300?img=3', bio: 'Full-stack wizard specialized in React and Node.js.' },
  ],
  clients: [
    { id: '1', name: 'Google', logo: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/google.svg' },
    { id: '2', name: 'Spotify', logo: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/spotify.svg' },
    { id: '3', name: 'Airbnb', logo: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/airbnb.svg' },
    { id: '4', name: 'Stripe', logo: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/stripe.svg' },
    { id: '5', name: 'Nike', logo: 'https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/nike.svg' },
  ],
  awards: [
    { id: '1', title: 'Agency of the Year', organization: 'Awwwards', year: '2023', image: 'https://api.dicebear.com/7.x/initials/svg?seed=AW' },
    { id: '2', title: 'Best UI/UX Design', organization: 'Webby Awards', year: '2023', image: 'https://api.dicebear.com/7.x/initials/svg?seed=WA' },
    { id: '3', title: 'Top Developer', organization: 'Clutch', year: '2022', image: 'https://api.dicebear.com/7.x/initials/svg?seed=CL' },
  ],
  process: [
    { id: '1', title: 'Discovery', description: 'We dive deep into your business goals and user needs.', icon: 'Search' },
    { id: '2', title: 'Strategy', description: 'Blueprint of the project architecture and marketing funnel.', icon: 'Map' },
    { id: '3', title: 'Design', description: 'Crafting visual interfaces that captivate and engage.', icon: 'Palette' },
    { id: '4', title: 'Development', description: 'Clean, robust code that ensures performance and scalability.', icon: 'Code' },
    { id: '5', title: 'Launch', description: 'Seamless deployment to the live environment.', icon: 'Rocket' },
    { id: '6', title: 'Support', description: 'Ongoing maintenance to ensure sustained growth.', icon: 'Headphones' },
  ]
};