import React, { useState } from 'react';
import { useSite } from '../../context/SiteContext';
import { BlogPost } from '../../types';
import { Plus, Edit, Trash, X, Save, Wand2 } from 'lucide-react';

const AdminBlog = () => {
  const { data, updateData } = useSite();
  const [isEditing, setIsEditing] = useState(false);
  const [currentPost, setCurrentPost] = useState<BlogPost | null>(null);

  const handleEdit = (post: BlogPost) => {
    setCurrentPost(post);
    setIsEditing(true);
  };

  const handleCreate = () => {
    setCurrentPost({
      id: Date.now().toString(),
      title: '',
      author: 'Admin',
      date: new Date().toLocaleDateString(),
      excerpt: '',
      content: '',
      image: 'https://picsum.photos/800/600',
    });
    setIsEditing(true);
  };

  const handleDelete = (id: string) => {
    if (window.confirm('Are you sure you want to delete this post?')) {
      updateData({ blog: data.blog.filter(p => p.id !== id) });
    }
  };

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();
    if (!currentPost) return;

    const existingIndex = data.blog.findIndex(p => p.id === currentPost.id);
    let newBlog = [...data.blog];

    if (existingIndex >= 0) {
      newBlog[existingIndex] = currentPost;
    } else {
      newBlog = [currentPost, ...newBlog];
    }

    updateData({ blog: newBlog });
    setIsEditing(false);
  };

  // Mock AI Generation
  const handleAiGenerate = () => {
    if(!currentPost) return;
    setCurrentPost({
      ...currentPost,
      excerpt: "Generated by AI: A comprehensive look into digital transformation strategies...",
      content: "Generated by AI: This is a long-form placeholder for content generated by a Large Language Model. In a real production environment, this would call the Google Gemini API."
    });
  }

  return (
    <div>
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-3xl font-bold">Manage Blog Posts</h1>
        <button 
          onClick={handleCreate}
          className="bg-primary text-white px-4 py-2 rounded-lg flex items-center gap-2 hover:bg-primary/90 transition"
        >
          <Plus size={18} /> New Post
        </button>
      </div>

      {isEditing && currentPost ? (
        <div className="bg-white dark:bg-gray-800 p-8 rounded-xl shadow-lg border border-gray-100 dark:border-gray-700 mb-8 animate-fade-in-up">
          <div className="flex justify-between mb-6">
            <h2 className="text-xl font-bold">Editor</h2>
            <button onClick={() => setIsEditing(false)} className="text-gray-500 hover:text-red-500"><X /></button>
          </div>
          <form onSubmit={handleSave} className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block text-sm font-medium mb-2">Title</label>
                <input 
                  type="text" 
                  value={currentPost.title}
                  onChange={e => setCurrentPost({...currentPost, title: e.target.value})}
                  className="w-full p-3 rounded-lg border dark:bg-gray-700 dark:border-gray-600"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-2">Author</label>
                <input 
                  type="text" 
                  value={currentPost.author}
                  onChange={e => setCurrentPost({...currentPost, author: e.target.value})}
                  className="w-full p-3 rounded-lg border dark:bg-gray-700 dark:border-gray-600"
                />
              </div>
            </div>
            
            <div>
              <label className="block text-sm font-medium mb-2">Image URL</label>
              <input 
                type="text" 
                value={currentPost.image}
                onChange={e => setCurrentPost({...currentPost, image: e.target.value})}
                className="w-full p-3 rounded-lg border dark:bg-gray-700 dark:border-gray-600"
              />
              {currentPost.image && <img src={currentPost.image} alt="Preview" className="mt-2 h-32 object-cover rounded-lg" />}
            </div>

            <div>
              <div className="flex justify-between items-center mb-2">
                  <label className="block text-sm font-medium">Excerpt</label>
                  <button type="button" onClick={handleAiGenerate} className="text-xs flex items-center gap-1 text-primary font-bold hover:underline"><Wand2 size={12}/> Generate with AI</button>
              </div>
              <textarea 
                value={currentPost.excerpt}
                onChange={e => setCurrentPost({...currentPost, excerpt: e.target.value})}
                className="w-full p-3 rounded-lg border dark:bg-gray-700 dark:border-gray-600 h-20"
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-2">Full Content</label>
              <textarea 
                value={currentPost.content}
                onChange={e => setCurrentPost({...currentPost, content: e.target.value})}
                className="w-full p-3 rounded-lg border dark:bg-gray-700 dark:border-gray-600 h-64 font-mono text-sm"
              />
            </div>

            <div className="flex justify-end gap-4">
              <button type="button" onClick={() => setIsEditing(false)} className="px-6 py-2 rounded-lg border hover:bg-gray-100 dark:hover:bg-gray-700">Cancel</button>
              <button type="submit" className="bg-primary text-white px-6 py-2 rounded-lg hover:bg-primary/90 flex items-center gap-2">
                <Save size={18} /> Save Post
              </button>
            </div>
          </form>
        </div>
      ) : (
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 overflow-hidden">
          <table className="w-full text-left">
            <thead className="bg-gray-50 dark:bg-gray-700 border-b dark:border-gray-600">
              <tr>
                <th className="p-4 font-medium text-gray-500 dark:text-gray-300">Post Title</th>
                <th className="p-4 font-medium text-gray-500 dark:text-gray-300">Author</th>
                <th className="p-4 font-medium text-gray-500 dark:text-gray-300">Date</th>
                <th className="p-4 font-medium text-right text-gray-500 dark:text-gray-300">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 dark:divide-gray-700">
              {data.blog.map(post => (
                <tr key={post.id} className="hover:bg-gray-50 dark:hover:bg-gray-700/50">
                  <td className="p-4 font-medium">{post.title}</td>
                  <td className="p-4 text-gray-500 dark:text-gray-400">{post.author}</td>
                  <td className="p-4 text-gray-500 dark:text-gray-400">{post.date}</td>
                  <td className="p-4 text-right space-x-2">
                    <button onClick={() => handleEdit(post)} className="text-blue-500 hover:bg-blue-50 p-2 rounded-full transition"><Edit size={18} /></button>
                    <button onClick={() => handleDelete(post.id)} className="text-red-500 hover:bg-red-50 p-2 rounded-full transition"><Trash size={18} /></button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};

export default AdminBlog;